const express = require("express");
const catrouter = require("./categories/categories.router");
const userrouter = require("./usertable/user.router");
const productrouter = require("./productstable/product.router");
const vendorouter = require("./vendortable/vendorrouter");
const authMiddleware = require("../../middlewares/authenticateToken");
const postcartrouter = require("./postcarttable/postcart.router");
const getcartrouter = require("./getcarttable/getcart.router");
const importproduct = require("./productstable/importproduct");
const decryptPayload = require("../../middlewares/decrypt");
const getStatus = require("./usertable/getstatus");
const app = express();
const dashboard = express.Router();
dashboard.use("/vendor", vendorouter);
dashboard.use("/categories", catrouter);
dashboard.use("/product", productrouter);
dashboard.use("/importdata", importproduct);
dashboard.use("/userdata", authMiddleware, userrouter);
dashboard.use("/postcart", authMiddleware, postcartrouter);
dashboard.use("/status", authMiddleware, decryptPayload, getStatus);
dashboard.use("/getcarts", authMiddleware, getcartrouter);
module.exports = dashboard;
